name: GCF TEST
on: [push]
jobs:
  gcf_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: gcd test
        id: gcd_test
        run: |
          ./gcd_test.sh
      - name: check result
        run: echo $CONTEXT
        env:
          CONTEXT: ${{ toJSON(steps.gcd_test) }}